// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cugahxapyyeosnshdqtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1Z2FoeGFweXllb3Nuc2hkcXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODg1ODUsImV4cCI6MjA2MDU2NDU4NX0.DmSzoEGHF_BD9dzGiulxUygbK9w7FCRH9_FmB7IkVBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);